name: "Test"
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - uses: cachix/cachix-action@v14
      with:
        name: ksvnixcachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: echo "Branch name: ${{ github.ref_name }}"
    - run: nix build .
    - run: nix develop --command python3 --version
