name: "Test"
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Determinate Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
          determinate: true
        
    - run: echo "Branch name is ${{ github.ref }}"

    - run: nix flake check

    - name: Shell check
      run: nix build .#devShells.x86_64-linux.default --dry-run

    - name: Build check
      run: nix build . --dry-run

    - name: OCI image Build check
      run: nix build .#dockerLayered --dry-run