name: "Test"
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - uses: cachix/cachix-action@v14
      with:
        name: ksvnixcachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: echo "Branch name is ${{ github.ref }}"
    - name: Shell check
      run: nix develop --command python3 --version
    - name: Build check
      run: nix build .
    - name: Docker Build
      run: nix build .#dockerImage
    - name: OCI formatting
      run: |
          mkdir oci-image
          nix shell -p nixpkgs#tar --command tar -xf result -C oci-image
    - name: image push to ghcr with skopeo
      if: success() && github.event_name == 'push'
      run: |
            nix shell -p nixpkgs#skopeo --command \
              skopeo copy \
              --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
              oci:oci-image \
              ghcr://ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.repository }}-${{ github.sha }}