name: Update Trivy DB Cache
permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    # Run at 13:00 UTC every Monday
    - cron: '0 13 * * 1'
  workflow_dispatch:  # Allow manual trigger when needed

jobs:
  update-trivy-db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ksvnixcachix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      
      - name: Restore Trivy cache
        uses: actions/cache/restore@v4
        with:
          path: .trivycache
          key: trivy-db-cache
          restore-keys: |
            trivy-db-cache-
      
      - name: Update Trivy DB
        run: |
          mkdir -p .trivycache
          nix run nixpkgs#trivy -- \
          image \
          --download-db-only \
          --cache-dir .trivycache
      
      - name: Verify DB Update
        run: |
          echo "Trivy DB updated at: $(date)"
          ls -la .trivycache/db
          echo "DB metadata:"
          cat .trivycache/db/metadata.json || echo "Metadata file not found"
      
      - name: Save updated Trivy cache
        uses: actions/cache/save@v4
        with:
          path: .trivycache
          key: trivy-db-cache